apiVersion: v1
kind: Pod
metadata: 
  name: pod-config
spec:
  containers:
  - name: nginx
    image: nginx
    envFrom:
    - configMapRef:
      name: myconfig

# kind: Pod
# apiVersion: v1
# metadata:
#   name: pod-config
# spec:
#   containers:
#   - name: nginx
#     image: nginx
#     envFrom:
#     - configMapRef:
#         name: myconfig