apiVersion: v1
kind: Service
metadata:
  name: nginx
spec: 
  selector:   # lables are used as selectors 
    project: expense
    component: backend
    environment: dev
    version: "v1"
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80

---
apiVersion: v1
kind: Pod
metadata:
  name: backend
  lables:
    project: expense
    component: backend
    environment: dev
    version: "v1"
spec:
  containers:
  - name: nginx
    image: nginx