apiVersion: app/v1
kind: ReplicaSet
metadata: 
  name: nginx
  # these lables replica set lables
  labels:
    app: frontend
    tier: web
spec: 
  replicas: 3
  selector: 
    # replicaset uses these labels to find the pods for creating desired number of replicas
    matchLabels: 
      app: frontend
      teir: web
  template:
    metadata:
      labels:
        app: frontend
        teir: web
    spec:
      containers:
        name: nginx
        image: nginx
# pod is a subset of replica, so no need of mentioning apiVersion and kind
