apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
    teir: frontend
    environment: deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      teir: frontend
      environment: deployment
  template:
    metadata:
      labels:
        app: nginx
        teir: frontend
        environment: deployment
    spec:
      containers:
      - name: nginx
        image: parthureddy3/deployment:1.0.0
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: nginx
spec: 
  type: LoadBalancer
  selector:   # lables are used as selectors 
    app: nginx
    teir: frontend
    environment: deployment
  ports:
    - protocol: TCP
      port: 80 #service port
      targetPort: 80
      nodePort: 30008