apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: expense
spec:
  # one pod can contain multiple containers
  serviceAccount: expense-mysql-secret
  containers:
    - name: nginx
      image: nginx
  initContainers:
  