apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod-init
  labels:
    app.kubernetes.io/name: MyApp
spec:
  # one pod can contain multiple containers
  containers:
  - name: nginx
    image: nginx
  initContainers:
  - name: init-myservice
    image: busybox:1.28
    command: ['sh', '-c', "until nslookup googfffle.com; do echo waiting for myservice; sleep 10; done"]